### ISSUE TITLE
Fix rendering issue with axles after reloading the world

### ISSUE THREAD

**Issue by Josharias** [Terasology/IRLCorp#15]
To reproduce:
1. Place an axle block
2. exit the world
3. Reloading the world
4. The axle will no longer appear in the world, even though its hitbox is still there and you can break and re-place it

This is caused by the client side entity generation not happening (the axles are an entity created at runtime that has a meshcomponent).

**Comment by jdrueckert** [comment]
This issue is no longer reproducible. Axles appear in the world on reloading.
